# outputs.conf

# Monitor principal conectado por HDMI
output HDMI-A-1 {
    mode 1920x1080@144Hz
    bg /home/lonso/Documentos/fondo.jpg fill
    adaptive_sync off
    allow_tearing yes
}

# Optimización extrema de latencia nativa sin VRR
output HDMI-A-1 max_render_time off

# Outputs desconectados — definidos por si se conectan
output eDP-1 resolution 1920x1080
output DP-1  resolution 1920x1080
